// Generated by CoffeeScript 1.6.3
(function() {
  require(['testcomm'], function(TestComm) {
    var assert, comm;
    mocha.setup('bdd');
    comm = null;
    assert = function(expr, msg) {
      if (msg == null) {
        msg = 'failed';
      }
      if (!expr) {
        throw new Error(msg);
      }
    };
    beforeEach(function() {
      return comm = new TestComm;
    });
    describe('CommTest', function() {
      return describe('イベントの付け外し', function() {
        it('ちゃんとつくか', function(done) {
          comm.on('success', 'success', function() {
            return done();
          });
          return comm.doen('success');
        });
        it('重複してつかないか', function(done) {
          var cnt, onComplete;
          cnt = 0;
          onComplete = function() {
            cnt++;
            if (cnt > 1) {
              return assert(false);
            }
          };
          comm.on('success', 'success', onComplete);
          comm.on('success', 'success', onComplete);
          comm.on('success', 'success', function() {
            return done();
          });
          return comm.doen('success');
        });
        it('つけわけができるか', function(done) {
          comm.on('success', 'success', function() {
            return assert(false);
          });
          comm.on('failure', 'success', function() {
            return assert(false);
          });
          comm.on('failure', 'failure', function() {
            return done();
          });
          return comm.doen('failure');
        });
        return it('正常にはずせるか', function(done) {
          var onComplete;
          onComplete = function() {
            return assert(false);
          };
          comm.on('success', 'success', onComplete);
          comm.off('success', 'success', onComplete);
          comm.on('success', 'success', function() {
            return done();
          });
          return comm.doen('success');
        });
      });
    });
    return mocha.run();
  });

}).call(this);
