// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['../comm.js'], function(Comm) {
    var TestComm, _ref;
    return TestComm = (function(_super) {
      __extends(TestComm, _super);

      function TestComm() {
        _ref = TestComm.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      TestComm.prototype._url = 'dummy';

      TestComm.prototype._actions = {
        success: {
          method: 'get'
        },
        failure: {
          method: 'get'
        }
      };

      return TestComm;

    })(Comm);
  });

}).call(this);
